[phases.setup]
nixPkgs = ['nodejs_18', 'python311', 'python311Packages.pip']

[phases.install]
cmds = [
    'npm ci',
    'pip install -r services/requirements.txt',
    'playwright install chromium',
    'playwright install-deps chromium'
]

[start]
cmd = 'node server.js'
